name: SimpleEconomy
version: 1.0.0
main: rark\simple_economy\Main
api: 4.0.0
author: RarkHopper
permissions:
  simple_economy:
    description: "Allows the user to do all example things"
    default: op # can also be false, or op
    children:
      simple_economy.command:
        description: "Allows the user to run all example commands"
        default: op # can also be false, or op
        children:
          simple_economy.command.op:
            description: "Allows the user to run the example command"
            default: op # can also be false, or op
          simple_economy.command.public:
            description: "Allows the user to run the example command"
            default: true # can also be false, or op
